services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=UTC+1

  # portainer:
  #   container_name: portainer
  #   image: portainer/portainer-ce:latest
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - portainer_data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "9000:9000"
  #     - "9443:9443"

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: bridge
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      TZ: UTC+1
      FTLCONF_dns_upstreams: '1.1.1.1;1.0.0.1'
      # Google upstreams fallback option:
      # FTLCONF_dns_upstreams: '8.8.8.8;8.8.4.4'
    volumes:
      - pihole_config:/etc/pihole
      - pihole_dnsmasq_config:/etc/dnsmasq.d
    ports:
      - "5453:53/tcp"
      - "5453:53/udp"
      - "8081:80/tcp"
      - "8443:443/tcp"

volumes:
  # portainer_data:
  pihole_config:
  pihole_dnsmasq_config:

